export const INDEXED_DB_DATABASE_NAME = 'vmanDB2'
export const INDEXED_DB_DATABASE_NAME2 = 'vmanDB'
export const INDEXED_DB_VERSION = 'indexedDBVersion'
export const OBJECTSTORE_VA_QUESTIONS = 'odk_questions'
export const OBJECTSTORE_ICD10 = 'icd10'
export const OBJECTSTORE_CCVA_RESULTS = 'ccva_results'
export const INDEX_DB_OBJECTSTORES = [OBJECTSTORE_VA_QUESTIONS, OBJECTSTORE_ICD10, OBJECTSTORE_CCVA_RESULTS]