export const PCVA_MODULE_ACCESS: string = 'PCVA_MODULE_VIEW';
export const PCVA_CREATE_ICD10_CODES: string = 'PCVA_CREATE_ICD10_CODES';
export const PCVA_VIEW_ICD10_CODES: string = 'PCVA_VIEW_ICD10_CODES';
export const PCVA_UPDATE_ICD10_CODES: string = 'PCVA_UPDATE_ICD10_CODES';
export const PCVA_DELETE_ICD10_CODES: string = 'PCVA_DELETE_ICD10_CODES';
export const PCVA_CREATE_ICD10_CATEGORIES: string = 'PCVA_CREATE_ICD10_CATEGORIES';
export const PCVA_VIEW_ICD10_CATEGORIES: string = 'PCVA_VIEW_ICD10_CATEGORIES';
export const PCVA_UPDATE_ICD10_CATEGORIES: string = 'PCVA_UPDATE_ICD10_CATEGORIES';
export const PCVA_DELETE_ICD10_CATEGORIES: string = 'PCVA_DELETE_ICD10_CATEGORIES';

// USERS MODULE
export const USERS_MODULE_VIEW: string = 'USERS_MODULE_VIEW';
export const USERS_CREATE_USER: string = 'USERS_CREATE_USER';
export const USERS_UPDATE_USER: string = 'USERS_UPDATE_USER';
export const USERS_VIEW: string = 'USERS_VIEW';
export const USERS_DEACTIVATE_USER: string = 'USERS_DEACTIVATE_USER';
export const USERS_ASSIGN_ROLES: string = 'USERS_ASSIGN_ROLES';
export const USERS_CREATE_ROLES: string = 'USERS_CREATE_ROLES';
export const USERS_DELETE_ROLES: string = 'USERS_DELETE_ROLES';
export const USERS_UPDATE_ROLES: string = 'USERS_UPDATE_ROLES';
export const USERS_VIEW_ROLES: string = 'USERS_VIEW_ROLES';
export const USERS_VIEW_PRIVILEGES: string = 'USERS_VIEW_PRIVILEGES';
export const USERS_LIMIT_DATA_ACCESS: string = 'USERS_LIMIT_DATA_ACCESS';
export const USERS_UPDATE_ACCESS_LIMIT_LABELS: string = 'USERS_UPDATE_ACCESS_LIMIT_LABELS';
